openapi: 3.0.0
info:
  title: Sample API
  description: A simple example Swagger YAML file
  version: 1.0.0
paths:
  http://localhost:5001/user:
    get:
      summary: Get a list of users
      description: Retrieves a list of user profiles.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: John
                - id: 2
                  name: Alice
    post:
      summary: Create a new user
      description: Creates a new user profile.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        '201':
          description: User created successfully
components:
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
      required:
        - name
        - email
